# config.yaml
train:
  lr: 0.0001
  betas: [0.9, 0.999]
  optimizer: "Adam"
  epochs: 100
  batch_size: 32
  sample_rate: 24000
  n_fft: 1024
  hop_length: 256
  n_mels: 100
  win_length: 1024  # 需要跟n_fft一致

data:
  train_data_path: "/tmp/芙宁娜"
  val_split: 0.2
